<form action="/login" method="post" class="w-100" style="max-width: 350px;">
    <div class="mb-3 w-100">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" name="email" id="email" class="form-control" required>
    </div>

    <div class="mb-3 w-100">
        <label for="password" class="form-label">Senha</label>
        <input type="password" name="password" id="password" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary w-100">Entrar</button>
</form>
