<form action="/login" method="POST" class="w-100" style="max-width: 350px;">
    <div class="mb-3 w-100">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" id="email" name="user[email]" class="form-control" value="fulano@example.com" required>
    </div>

    <div class="mb-3 w-100">
        <label for="password" class="form-label">Senha</label>
        <input type="password" id="password" name="user[password]" class="form-control" value="123456" required>
    </div>

    <button type="submit" class="btn btn-primary w-100">Entrar</button>
</form>
