<div class="container py-5">

    <div class="d-flex justify-content-between align-items-center mb-5 position-relative">

        <a href="/events" class="btn btn-outline-primary">
            <i class="bi bi-arrow-left"></i> Back to Events
        </a>

        <button type="button" class="btn btn-outline-primary">
            <i class="bi bi-plus text-danger-custom fs-5"></i>
        </button>

    </div>

</div>
