<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>

    <header class="bg-primary shadow-sm p-3 position-fixed top-0 w-100 d-flex justify-content-between align-items-center" style="z-index: 1000;">
        <div class="d-flex align-items-center gap-2">
            <i class="fs-4 text-white"></i>
            <strong class="text-white fs-4 mb-0">EchoEventus</strong>
        </div>

        <div class="position-absolute start-50 translate-middle-x">
            <strong class="text-white fs-4 mb-0"><?= $title ?></strong>
        </div>

        <div class="d-flex align-items-center gap-2">
            <?php if (isset($this->current_user) && $this->current_user): ?>
                <span class="text-white me-2"><?= htmlspecialchars($this->current_user->name) ?></span>
                <a href="/events/new" class="btn btn-header-outline d-flex align-items-center gap-1">
                    <i class="bi bi-plus"></i> Create Event
                </a>
                <a href="/logout" class="btn btn-header-outline">
                    <i class="bi bi-arrow-left"></i> Logout
                </a>
            <?php else: ?>
                <a href="/login" class="btn btn-header-outline">
                    <i class="bi bi-box-arrow-in-right"></i> Login
                </a>
            <?php endif; ?>
        </div>
    </header>

    <main class="mt-5 pt-5">
        <div class="row justify-content-center">
            <section class="text-center">
                <?php require '_flash_message.phtml'; ?>
                <?php require $view ?>
            </section>
        </div>
    </main>

</body>


</html>