<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body class="m-0">
    <main class="d-flex justify-content-center align-items-center vh-100">
        <div class="row shadow-lg card-login h-75 w-75">
            
            <div class="col-6 text-center d-none d-md-flex flex-column justify-content-center align-items-center bg-primary-custom text-secondary-custom p-4 card-logo-login">
                <img src="/assets/images/defaults/logo.png" alt="Logo" class="img-fluid mb-3" style="max-width: 150px;">
            </div>
            
            <div class="col-6 p-4 d-flex flex-column justify-content-center align-items-center">
                <?php require '_flash_message.phtml'; ?>
                <h1 class="mb-3"> <?= $title ?> </h1>
                <?php require $view; ?>
            </div>
        </div>
    </main>
</body>

</html>