<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/login.css">
</head>

<body class="bg-light d-flex justify-content-center align-items-center vh-100">
    <main class="container" style="max-width: 450px;">
        <div class="card shadow-sm border-0 rounded-4 p-5">
            <div class="text-center mb-5">
                <h1 class="fw-bold text-primary"><?= $title ?></h1>
                <p class="text-muted mb-0">Enter your credentials to continue</p>
            </div>

            <?php require '_flash_message.phtml'; ?>

            <?php require $view; ?>
        </div>
    </main>
</body>

</html>